name: Rust

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [nightly]
    steps:
      - name: Setup Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
          components: clippy,rustfmt

      - name: Load Rust Cache
        uses: Swatinem/rust-cache@v1

      - uses: actions/checkout@v2

      - name: Run tests
        run: cargo test --verbose

      - name: Build
        run: cargo build --verbose --release

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: db-extractor
          path: target/release/db-extractor
